### ISSUE TITLE
Version 0.2 not in Open Store

### ISSUE THREAD

**Issue by roydenyates** [rschroll/bookmarks#1]
Hi, visiting here I discovered an update that has not reached Open Store from where I first encountered the scope.  Brilliant stuff.  On the Meizu MX4, version 0.1 has overly large icons but the concept is an absolute winner.

**Comment by rschroll** [comment]
Whoops!  The open store submission process isn't automated, and it 
looks like we dropped the ball on the new version.  I've restarted the 
process; hopefully it'll be updated in a day or so.

> On the Meizu MX4, version 0.1 has overly large icons but the concept 
> is an absolute winner.

Unfortunately, this is something I can't fix.  I've made the icons as 
small as I can.  They're still larger than those in the application 
launcher because _Unity 8 hardcodes a different size for that scope_!

I wish I was making this up, but no.  Someone thought this was an 
intelligent thing to do.  There's a bug, but, predictably, no real 
action on solving it: https://bugs.launchpad.net/ubuntu-ux/+bug/1490388.

Bah!

**Comment by roydenyates** [comment]
Thank you. Bah indeed! Small Team Blues......

**Comment by roydenyates** [comment]
Sorry to be a PIA(ss), but it has not appeared....

**Comment by rschroll** [comment]
Finally got in contact with the Open Store maintainer, and the new version is up.  Sorry for the long delay.
